name: vita_apps
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.15
  forge_annotation: ^0.0.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.6.1
  hive: ^2.2.3
  injectable: ^2.5.0
  path_provider: ^2.1.5
  sizer: ^3.0.5
  skeletonizer: ^1.4.2
dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  injectable_generator: ^2.6.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env.development
    - .env.production
flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  assets:
    exclude:
      - .env.development
      - .env.production
